### ISSUE TITLE
fractional spacing in Pango 1.44

### ISSUE THREAD

**Issue by mbutterick** [lexi-lambda/blackboard#1]
IIRC Racket still ships with Pango 1.42. In July 2019 Pango 1.44 added support for [fractional spacing](https://blogs.gnome.org/mclasen/2019/07/27/more-text-rendering-updates/). Roughly, fractional spacing allows glyphs to be positioned at something other than a pixel boundary, which makes the intercharacter spacing much more accurate, especially at small sizes. (This is why any text set with `racket/draw` looks a little janky and 1990s-ish.)

In this screen grab, the first three lines are drawn with Racket, and the fourth with a Mac OS TextEdit window:

![Screen Shot 2017-07-18 at Jul 18  5 12 16 PM](https://user-images.githubusercontent.com/1425051/156491014-e17597d9-2b07-4308-af7f-4b7891848d2f.gif)

IMHO moving Racket onto Pango 1.44 would have a hugely positive effect on `racket/draw` and `racket/gui` etc. (Of course I’m leaving aside whatever other complications might exist, since I am a one-issue voter.) Given the degree of refinement you're trying to achieve, maybe also `blackboard`.

**Comment by lexi-lambda** [comment]
I agree—and I commented on something similar in https://github.com/racket/draw/issues/38#issuecomment-1020758216. I think this is morally more of an upstream `racket/draw` issue, but it’s still technically relevant here, since `blackboard` currently sets up its own Pango context, anyway. The right fix is still probably to add this functionality to `racket/draw` first, though, then have `blackboard` use the upstream FFI definition.
